<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="0" total="4" passed="4">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="236" started-at="2013-10-11T18:52:59Z" finished-at="2013-10-11T18:53:00Z">
    <groups>
      <group name="business">
        <method signature="BackOfficeServiceTest.createNewEntryInvalidData()[pri:0, instance:gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest@4839e5b5]" name="createNewEntryInvalidData" class="gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest"/>
        <method signature="BackOfficeServiceTest.createNewEntryWithExistingEntity()[pri:0, instance:gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest@4839e5b5]" name="createNewEntryWithExistingEntity" class="gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest"/>
        <method signature="BackOfficeServiceTest.getCategories()[pri:0, instance:gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest@4839e5b5]" name="getCategories" class="gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest"/>
        <method signature="BackOfficeServiceTest.saveEntryCategory()[pri:0, instance:gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest@4839e5b5]" name="saveEntryCategory" class="gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest"/>
      </group> <!-- business -->
    </groups>
    <test name="Default test" duration-ms="236" started-at="2013-10-11T18:52:59Z" finished-at="2013-10-11T18:53:00Z">
      <class name="gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest@4839e5b5]" name="setUp" is-config="true" duration-ms="207" started-at="2013-10-11T21:52:59Z" finished-at="2013-10-11T21:53:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="createNewEntryInvalidData()[pri:0, instance:gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest@4839e5b5]" name="createNewEntryInvalidData" duration-ms="5" started-at="2013-10-11T21:53:00Z" finished-at="2013-10-11T21:53:00Z">
          <exception class="gr.bytecode.services.visitorphonebook.web.exceptions.InvalidDataException">
            <message>
              <![CDATA[Mock String]]>
            </message>
            <full-stacktrace>
              <![CDATA[gr.bytecode.services.visitorphonebook.web.exceptions.InvalidDataException: Mock String
	at gr.bytecode.services.visitorphonebook.services.BackOfficeService.validateEntry(BackOfficeService.java:332)
	at gr.bytecode.services.visitorphonebook.services.BackOfficeService.createNewEntry(BackOfficeService.java:119)
	at gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest.createNewEntryInvalidData(BackOfficeServiceTest.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- gr.bytecode.services.visitorphonebook.web.exceptions.InvalidDataException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewEntryInvalidData -->
        <test-method status="PASS" signature="createNewEntryWithExistingEntity()[pri:0, instance:gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest@4839e5b5]" name="createNewEntryWithExistingEntity" duration-ms="2" started-at="2013-10-11T21:53:00Z" finished-at="2013-10-11T21:53:00Z">
          <exception class="gr.bytecode.services.visitorphonebook.web.exceptions.EntityExistsException">
            <message>
              <![CDATA[Mock String]]>
            </message>
            <full-stacktrace>
              <![CDATA[gr.bytecode.services.visitorphonebook.web.exceptions.EntityExistsException: Mock String
	at gr.bytecode.services.visitorphonebook.services.BackOfficeService.validateEntry(BackOfficeService.java:367)
	at gr.bytecode.services.visitorphonebook.services.BackOfficeService.createNewEntry(BackOfficeService.java:119)
	at gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest.createNewEntryWithExistingEntity(BackOfficeServiceTest.java:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- gr.bytecode.services.visitorphonebook.web.exceptions.EntityExistsException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewEntryWithExistingEntity -->
        <test-method status="PASS" signature="getCategories()[pri:0, instance:gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest@4839e5b5]" name="getCategories" duration-ms="4" started-at="2013-10-11T21:53:00Z" finished-at="2013-10-11T21:53:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getCategories -->
        <test-method status="PASS" signature="saveEntryCategory()[pri:0, instance:gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest@4839e5b5]" name="saveEntryCategory" duration-ms="0" started-at="2013-10-11T21:53:00Z" finished-at="2013-10-11T21:53:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- saveEntryCategory -->
      </class> <!-- gr.bytecode.services.visitorphonebook.services.BackOfficeServiceTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
